defaults: &defaults
  app_name: "sysjust"
  domain: "http://sysjust.summers.com.tw"    
  admin_emails: 
    - "admin@sysjust.com.tw"
  google_analytics_key: ""
  default_logo_url: "/logo.png"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults